server:
  port: 80812

spring:
  datasource:
    url: jdbc:postgresql://192.168.4.46:5432/genesis
    username: genesis
    password: genesis
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
